### ISSUE TITLE
go version

### ISSUE THREAD

**Issue by demesm** [Kasmetski/auto-hard-reset#1]
Is there a specific version of go needed? Having issues using go build *.go

**Comment by Kasmetski** [comment]
It shouldn't have problems. I've write the code on version 1.8 but prebuild it with version 1.8.3 without problem. Could you give me more information about your system and the error?

Thank you.

**Comment by demesm** [comment]
I had pulled down the default version available to pi3, way outdated. Removed everything and its working perfect..thanks so much for this 👍

**Comment by Kasmetski** [comment]
Thank you for the information. I will update the info with required version.
Regards
