### ISSUE TITLE
Just a general question

### ISSUE THREAD

**Issue by denellum** [Kasmetski/auto-hard-reset#3]
In the image on your readme, which output of the relay would you connect to the mobo? loving this project and setting it up currently! Just don't want to break anything.

**Comment by denellum** [comment]
Edit : got it working, now it is saying a host is online when it's not.

**Comment by Kasmetski** [comment]
What is the output when you type "ping 192.168.0.XX" (ip of the machine)?

**Comment by Kasmetski** [comment]
I'm closing the issue. If you have same problem in the future comment here or open a new one.
