### ISSUE TITLE
which output of the relay would you connect to the mobo?

### ISSUE THREAD

**Issue by codesport** [Kasmetski/auto-hard-reset#4]
@Kasmetski Thanks for creating this.  

Would you provide more info on which pins to connect from the relay to the motherboard?

Looks like a high-level connection would be like this:

RasberryPi -> 5v Relay --> mobo (which pins from the relay and which pins on the mobo)?

Thanks in advance!

**Comment by Kasmetski** [comment]
Hello,

I know there should be a guide, but everytime I forgot to take pictures of the setup when I'm in the farm...

About the high-level connection you are right. 
about the other.. each relay have 3 outputs, you should connect to the left and the center one (when they are front of you)
on mobo connect on two pins where you connect the turn on button

If my explanation wasn't good enough I can take a pic of relay which I have here.

**Comment by codesport** [comment]
@Kasmetski, thanks for the follow-up.  If it's not too much trouble perhaps you can post a photo of the 5v relay outputs that need to be connected to the mobo. I'm sure it would benefit others who are new to IoT automation. 

And, thanks for pointing out the below. This is key:

> on mobo connect on two pins where you connect the turn on button

**Comment by Kasmetski** [comment]
I will post pictures with info tonight. Hope it helps. because my setup is working in the farm and I don't have many parts here with me.

**Comment by codesport** [comment]
Thanks.  Will be more than happy to update your ReadMe with these clarifications via a pull request. Just give a ping when you're able to post the photos

**Comment by Kasmetski** [comment]
I forgot about the photos. Sorry.
I will take a them when I got home later today.

**Comment by codesport** [comment]
No worries.  

What board and parts do you suggest to monitor and control environmental settings such as temperature, humidity, and smoke detection?

**Comment by Kasmetski** [comment]
Looks like I don't have any jumpers at home, but I use simple wires for the picture. You should connect jumpers to this outputs
[![photoooo.jpg](https://s1.postimg.org/4td8h7ewy7/photoooo.jpg)](https://postimg.org/image/19rarec763/)

**Comment by codesport** [comment]
Thanks. When time permits will do a pull request with suggestions/enhancements for your ReadME.

**Comment by Kasmetski** [comment]
Thanks in advance for your contribution. 

I'm closing this issue, if there is something else you can write below.
Thanks
